---
:api_key: 3280ffb018aa04701751662d93488378
:password: ed017a6c7167f977c29a8920c216abc0
:store: retro-spares.myshopify.com
:theme_id: 109674179
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
